language: python

python:
  - 3.6

services:
  - docker

env:
  matrix:
    - SINGLE_TEST_SETUP=mercury/icat:3.3.1
    - SINGLE_TEST_SETUP=mercury/icat:4.1.8
    - SINGLE_TEST_SETUP=mercury/icat:4.1.9
    - SINGLE_TEST_SETUP=mercury/icat:4.1.10

before_install:
  - pip install nose
  - pip install nose-exclude
  - pip install codecov

install:
  - pip install -r test_requirements.txt

script:
  - nosetests -v
