language: python

python:
  - 3.5

services:
  - docker

env:
  matrix:
    - SINGLE_TEST_SETUP=mercury/icat:3.3.1
    - SINGLE_TEST_SETUP=mercury/icat:4.1.8
    - SINGLE_TEST_SETUP=mercury/icat:4.1.9
    - SINGLE_TEST_SETUP=mercury/icat:4.1.10

install:
  - pip install -r test_requirements.txt

script:
  - nosetests -v --exclude-test=tests._common.create_tests_for_all_icat_setups
